import { db } from "./index";
import { items, clusters, entities, signals, alerts } from "./schema";
import { initDatabase } from "./init";
import { v4 as uuid } from "uuid";
import { sql } from "drizzle-orm";

// Track URLs to avoid duplicates
const seenUrls = new Set<string>();

// ─── Helpers ────────────────────────────────────────────────────────
function daysAgo(n: number): string {
  const d = new Date(); // Use current time, not a hardcoded date
  d.setDate(d.getDate() - n);
  d.setHours(Math.floor(Math.random() * 14) + 8); // 8am-10pm
  d.setMinutes(Math.floor(Math.random() * 60));
  return d.toISOString();
}

function compositeScore(importance: number, novelty: number, credibility: number, impact: number, practical: number): number {
  return Math.round((importance * 0.3 + novelty * 0.2 + credibility * 0.15 + impact * 0.25 + practical * 0.1) * 10) / 10;
}

// ─── IDs ────────────────────────────────────────────────────────────
// Pre-generate cluster IDs so items can reference them
const clusterIds = {
  gpt5: uuid(),
  claude4: uuid(),
  gemini2_5: uuid(),
  llama4: uuid(),
  eu_ai_act: uuid(),
  agi_debate: uuid(),
  open_source_models: uuid(),
  ai_agents: uuid(),
  multimodal: uuid(),
  ai_funding: uuid(),
};

// Pre-generate entity IDs
const entityIds = {
  openai: uuid(),
  anthropic: uuid(),
  google: uuid(),
  meta: uuid(),
  mistral: uuid(),
  stability: uuid(),
  cohere: uuid(),
  deepmind: uuid(),
  nvidia: uuid(),
  huggingface: uuid(),
  gpt5: uuid(),
  claude4: uuid(),
  gemini2_5: uuid(),
  llama4: uuid(),
  mistral_large3: uuid(),
};

// Pre-generate item IDs so signals/alerts can reference them
const itemIds: string[] = [];
for (let i = 0; i < 75; i++) {
  itemIds.push(uuid());
}

async function seed() {
  console.log("Initializing database...");
  initDatabase();
  console.log("Seeding data...");

  // ─── Entities ───────────────────────────────────────────────────
  const entityData = [
    { id: entityIds.openai, name: "OpenAI", type: "company", description: "AI research lab behind GPT and ChatGPT", url: "https://openai.com", aliases: '["OAI"]', mentionCount: 28, lastMentioned: daysAgo(0) },
    { id: entityIds.anthropic, name: "Anthropic", type: "company", description: "AI safety company behind Claude", url: "https://www.anthropic.com", aliases: '[]', mentionCount: 22, lastMentioned: daysAgo(0) },
    { id: entityIds.google, name: "Google", type: "company", description: "Tech giant with Gemini AI models", url: "https://ai.google", aliases: '["Alphabet","Google DeepMind"]', mentionCount: 19, lastMentioned: daysAgo(0) },
    { id: entityIds.meta, name: "Meta", type: "company", description: "Social media company investing heavily in open-source AI", url: "https://ai.meta.com", aliases: '["Facebook"]', mentionCount: 16, lastMentioned: daysAgo(1) },
    { id: entityIds.mistral, name: "Mistral AI", type: "company", description: "French AI startup focused on open and efficient models", url: "https://mistral.ai", aliases: '[]', mentionCount: 8, lastMentioned: daysAgo(2) },
    { id: entityIds.stability, name: "Stability AI", type: "company", description: "Open-source generative AI company", url: "https://stability.ai", aliases: '[]', mentionCount: 5, lastMentioned: daysAgo(4) },
    { id: entityIds.cohere, name: "Cohere", type: "company", description: "Enterprise-focused AI company", url: "https://cohere.com", aliases: '[]', mentionCount: 6, lastMentioned: daysAgo(3) },
    { id: entityIds.deepmind, name: "DeepMind", type: "lab", description: "Google's AI research lab", url: "https://deepmind.google", aliases: '["Google DeepMind"]', mentionCount: 12, lastMentioned: daysAgo(1) },
    { id: entityIds.nvidia, name: "NVIDIA", type: "company", description: "Leading GPU manufacturer powering AI infrastructure", url: "https://nvidia.com", aliases: '["NVDA"]', mentionCount: 9, lastMentioned: daysAgo(1) },
    { id: entityIds.huggingface, name: "Hugging Face", type: "company", description: "Open-source AI platform and model hub", url: "https://huggingface.co", aliases: '["HF"]', mentionCount: 11, lastMentioned: daysAgo(0) },
    { id: entityIds.gpt5, name: "GPT-5", type: "model", description: "OpenAI's next-generation language model", url: "https://openai.com", aliases: '["gpt5","GPT5"]', mentionCount: 15, lastMentioned: daysAgo(0) },
    { id: entityIds.claude4, name: "Claude 4", type: "model", description: "Anthropic's latest model generation", url: "https://www.anthropic.com", aliases: '["claude-4","Claude4"]', mentionCount: 12, lastMentioned: daysAgo(1) },
    { id: entityIds.gemini2_5, name: "Gemini 2.5", type: "model", description: "Google's advanced multimodal model", url: "https://deepmind.google", aliases: '["gemini-2.5"]', mentionCount: 10, lastMentioned: daysAgo(0) },
    { id: entityIds.llama4, name: "Llama 4", type: "model", description: "Meta's open-weight language model", url: "https://ai.meta.com", aliases: '["LLaMA 4","llama-4"]', mentionCount: 14, lastMentioned: daysAgo(1) },
    { id: entityIds.mistral_large3, name: "Mistral Large 3", type: "model", description: "Mistral's flagship commercial model", url: "https://mistral.ai", aliases: '[]', mentionCount: 5, lastMentioned: daysAgo(5) },
  ];

  for (const e of entityData) {
    db.insert(entities).values(e).run();
  }

  // ─── Clusters ───────────────────────────────────────────────────
  const clusterData = [
    { id: clusterIds.gpt5, title: "GPT-5 Launch and Reception", summary: "OpenAI releases GPT-5 with major reasoning and multimodal improvements, sparking industry reactions.", category: "model", firstSeen: daysAgo(3), lastUpdated: daysAgo(0), itemCount: 8, peakScore: 95, trendVelocity: 12.5, entities: JSON.stringify(["OpenAI", "GPT-5"]), tags: '["gpt-5","openai","launch","reasoning"]' },
    { id: clusterIds.claude4, title: "Claude 4 Capabilities and Benchmarks", summary: "Anthropic's Claude 4 demonstrates strong coding, reasoning, and safety improvements.", category: "model", firstSeen: daysAgo(6), lastUpdated: daysAgo(1), itemCount: 6, peakScore: 90, trendVelocity: 8.2, entities: JSON.stringify(["Anthropic", "Claude 4"]), tags: '["claude-4","anthropic","safety","benchmarks"]' },
    { id: clusterIds.gemini2_5, title: "Gemini 2.5 Pro and Flash Updates", summary: "Google releases Gemini 2.5 Pro with improved long-context and coding abilities.", category: "model", firstSeen: daysAgo(5), lastUpdated: daysAgo(0), itemCount: 5, peakScore: 85, trendVelocity: 6.0, entities: JSON.stringify(["Google", "Gemini 2.5"]), tags: '["gemini","google","multimodal"]' },
    { id: clusterIds.llama4, title: "Llama 4 Open Release", summary: "Meta releases Llama 4 family including Scout and Maverick variants.", category: "model", firstSeen: daysAgo(8), lastUpdated: daysAgo(1), itemCount: 7, peakScore: 88, trendVelocity: 5.5, entities: JSON.stringify(["Meta", "Llama 4"]), tags: '["llama-4","meta","open-source","open-weights"]' },
    { id: clusterIds.eu_ai_act, title: "EU AI Act Implementation Begins", summary: "European Union begins enforcing portions of the AI Act with implications for global AI companies.", category: "policy", firstSeen: daysAgo(10), lastUpdated: daysAgo(2), itemCount: 4, peakScore: 72, trendVelocity: 2.1, entities: JSON.stringify(["EU"]), tags: '["regulation","eu","policy","compliance"]' },
    { id: clusterIds.agi_debate, title: "AGI Timeline Debate Intensifies", summary: "Researchers and executives debate near-term AGI claims following recent model breakthroughs.", category: "research", firstSeen: daysAgo(7), lastUpdated: daysAgo(1), itemCount: 5, peakScore: 68, trendVelocity: 3.8, entities: JSON.stringify(["OpenAI", "Anthropic", "DeepMind"]), tags: '["agi","timelines","debate","safety"]' },
    { id: clusterIds.open_source_models, title: "Open-Source Model Explosion", summary: "Surge of competitive open-source models challenging proprietary offerings.", category: "opensource", firstSeen: daysAgo(12), lastUpdated: daysAgo(0), itemCount: 6, peakScore: 78, trendVelocity: 4.5, entities: JSON.stringify(["Meta", "Mistral AI", "Hugging Face"]), tags: '["open-source","models","community"]' },
    { id: clusterIds.ai_agents, title: "AI Agent Frameworks Maturing", summary: "Multiple production-ready agent frameworks emerge as companies deploy autonomous AI systems.", category: "tool", firstSeen: daysAgo(9), lastUpdated: daysAgo(0), itemCount: 5, peakScore: 76, trendVelocity: 5.0, entities: JSON.stringify(["OpenAI", "Anthropic", "LangChain"]), tags: '["agents","frameworks","autonomous","tools"]' },
    { id: clusterIds.multimodal, title: "Multimodal AI Advances", summary: "Vision, audio, and video capabilities expanding rapidly across major models.", category: "research", firstSeen: daysAgo(11), lastUpdated: daysAgo(2), itemCount: 4, peakScore: 70, trendVelocity: 2.8, entities: JSON.stringify(["Google", "OpenAI"]), tags: '["multimodal","vision","video","audio"]' },
    { id: clusterIds.ai_funding, title: "AI Funding Mega-Rounds Continue", summary: "Record-breaking funding rounds for AI companies across infrastructure and applications.", category: "market", firstSeen: daysAgo(13), lastUpdated: daysAgo(1), itemCount: 4, peakScore: 65, trendVelocity: 1.5, entities: JSON.stringify(["NVIDIA"]), tags: '["funding","investment","startups","market"]' },
  ];

  for (const c of clusterData) {
    db.insert(clusters).values({ ...c, isDemo: true }).run();
  }

  // ─── Items ──────────────────────────────────────────────────────
  const itemData = [
    // GPT-5 cluster
    { idx: 0, title: "OpenAI Launches GPT-5 with Breakthrough Reasoning Capabilities", url: "https://openai.com/blog/gpt-5", source: "openai_blog", sourceType: "blog", publishedAt: daysAgo(2), category: "model", aiSummary: "OpenAI has released GPT-5, featuring significant improvements in multi-step reasoning, mathematical problem-solving, and code generation. The model achieves state-of-the-art results on MMLU, GPQA, and HumanEval benchmarks.", whyItMatters: "GPT-5 represents a meaningful step forward in reasoning ability, narrowing the gap between current AI systems and more general intelligence. Enterprise applications in analysis, coding, and research stand to benefit immediately.", whoShouldCare: "AI engineers, enterprise decision makers, researchers", tags: '["gpt-5","openai","reasoning","launch"]', company: "OpenAI", modelFamily: "GPT", clusterId: clusterIds.gpt5, importance: 95, novelty: 88, credibility: 95, impact: 92, practical: 85 },
    { idx: 1, title: "GPT-5 Benchmark Results: How It Compares to Claude 4 and Gemini 2.5", url: "https://techcrunch.com/2025/03/23/gpt-5-benchmarks", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(1), category: "model", aiSummary: "Independent benchmark testing shows GPT-5 leading on mathematical reasoning and code generation while Claude 4 maintains an edge in safety evaluations and long-context tasks. Gemini 2.5 Pro leads in multimodal benchmarks.", whyItMatters: "The competitive landscape between frontier models is tighter than ever, with each model showing distinct strengths rather than overall dominance.", whoShouldCare: "ML engineers, product teams choosing model providers", tags: '["gpt-5","benchmarks","comparison","claude-4","gemini"]', company: "OpenAI", modelFamily: "GPT", clusterId: clusterIds.gpt5, importance: 82, novelty: 65, credibility: 80, impact: 75, practical: 90 },
    { idx: 2, title: "GPT-5 API Pricing and Rate Limits Announced", url: "https://openai.com/blog/gpt-5-pricing", source: "openai_blog", sourceType: "blog", publishedAt: daysAgo(2), category: "model", aiSummary: "OpenAI sets GPT-5 pricing at $15/M input tokens and $60/M output tokens for the full model, with a GPT-5 Mini variant at $3/$12. Batch API discounts of 50% available.", whyItMatters: "Pricing signals OpenAI's strategy to maintain premium positioning. The Mini variant suggests awareness that cost is a barrier to adoption for many use cases.", whoShouldCare: "Engineering leads, CTOs, AI product managers", tags: '["gpt-5","pricing","api","costs"]', company: "OpenAI", modelFamily: "GPT", clusterId: clusterIds.gpt5, importance: 75, novelty: 55, credibility: 95, impact: 70, practical: 92 },
    { idx: 3, title: "Early GPT-5 Adopters Report 40% Improvement in Complex Task Completion", url: "https://www.theverge.com/2025/03/24/gpt-5-early-results", source: "the_verge_ai", sourceType: "news", publishedAt: daysAgo(0), category: "model", aiSummary: "Enterprise early access partners report significant gains in agentic workflows, multi-step analysis, and code migration tasks with GPT-5 compared to GPT-4 Turbo.", whyItMatters: "Real-world performance gains validate benchmark improvements and signal immediate practical value for enterprise AI deployments.", whoShouldCare: "Enterprise AI teams, solution architects", tags: '["gpt-5","enterprise","adoption","performance"]', company: "OpenAI", modelFamily: "GPT", clusterId: clusterIds.gpt5, importance: 78, novelty: 60, credibility: 75, impact: 80, practical: 88 },

    // Claude 4 cluster
    { idx: 4, title: "Anthropic Releases Claude 4 with Enhanced Safety and Reasoning", url: "https://www.anthropic.com/news/claude-4", source: "anthropic_blog", sourceType: "blog", publishedAt: daysAgo(5), category: "model", aiSummary: "Anthropic launches Claude 4, featuring Constitutional AI v2 for improved safety, 500K context window, and strong gains in coding, analysis, and instruction following.", whyItMatters: "Claude 4 demonstrates that safety-focused development can produce models competitive with less safety-constrained alternatives, validating Anthropic's approach.", whoShouldCare: "AI safety researchers, enterprise teams, developers", tags: '["claude-4","anthropic","safety","constitutional-ai"]', company: "Anthropic", modelFamily: "Claude", clusterId: clusterIds.claude4, importance: 92, novelty: 85, credibility: 92, impact: 88, practical: 82 },
    { idx: 5, title: "Claude 4 Sets New Standard for AI-Assisted Coding in SWE-Bench", url: "https://arstechnica.com/ai/2025/03/claude-4-swe-bench", source: "ars_technica_ai", sourceType: "news", publishedAt: daysAgo(4), category: "model", aiSummary: "Claude 4 achieves 72% on SWE-Bench Verified, surpassing previous state-of-the-art by 8 percentage points, demonstrating strong autonomous coding abilities.", whyItMatters: "The coding benchmark improvements suggest AI-assisted software development is approaching a new threshold of reliability for production use.", whoShouldCare: "Software engineers, engineering managers, developer tool companies", tags: '["claude-4","coding","swe-bench","benchmarks"]', company: "Anthropic", modelFamily: "Claude", clusterId: clusterIds.claude4, importance: 85, novelty: 78, credibility: 85, impact: 82, practical: 90 },
    { idx: 6, title: "Anthropic Publishes Claude 4 System Card with Novel Safety Evaluations", url: "https://www.anthropic.com/news/claude-4-system-card", source: "anthropic_blog", sourceType: "blog", publishedAt: daysAgo(5), category: "research", aiSummary: "Anthropic releases a comprehensive system card for Claude 4 including evaluations for deception, power-seeking, and autonomous capabilities, with new evaluation methodologies.", whyItMatters: "Sets a new bar for model transparency. The novel evaluation methodologies could become industry standard for responsible AI development.", whoShouldCare: "AI safety researchers, policymakers, AI governance teams", tags: '["claude-4","safety","system-card","transparency","evaluations"]', company: "Anthropic", modelFamily: "Claude", clusterId: clusterIds.claude4, importance: 80, novelty: 82, credibility: 94, impact: 75, practical: 55 },

    // Gemini 2.5 cluster
    { idx: 7, title: "Google Launches Gemini 2.5 Pro with 2M Token Context Window", url: "https://blog.google/technology/ai/gemini-2-5-pro", source: "google_ai_blog", sourceType: "blog", publishedAt: daysAgo(4), category: "model", aiSummary: "Google releases Gemini 2.5 Pro featuring a 2 million token context window, native multimodal processing, and improved tool use capabilities.", whyItMatters: "The 2M context window opens new use cases in document analysis, codebase understanding, and long-form content processing that were previously impractical.", whoShouldCare: "Developers building on Gemini, enterprise document processing teams", tags: '["gemini","google","long-context","multimodal"]', company: "Google", modelFamily: "Gemini", clusterId: clusterIds.gemini2_5, importance: 88, novelty: 80, credibility: 90, impact: 85, practical: 82 },
    { idx: 8, title: "Gemini 2.5 Flash: Fastest Frontier-Class Model at 300 Tokens/Second", url: "https://blog.google/technology/ai/gemini-2-5-flash", source: "google_ai_blog", sourceType: "blog", publishedAt: daysAgo(3), category: "model", aiSummary: "Gemini 2.5 Flash delivers near-Pro quality at 5x the speed and one-tenth the cost, targeting latency-sensitive and high-volume applications.", whyItMatters: "Speed and cost improvements make frontier-quality AI accessible for real-time applications like interactive assistants and live translation.", whoShouldCare: "Backend engineers, product managers, cost-conscious AI teams", tags: '["gemini","google","speed","efficiency","flash"]', company: "Google", modelFamily: "Gemini", clusterId: clusterIds.gemini2_5, importance: 78, novelty: 72, credibility: 88, impact: 75, practical: 88 },
    { idx: 9, title: "Gemini 2.5 Tops Multimodal Benchmarks with Native Image Understanding", url: "https://www.technologyreview.com/2025/03/22/gemini-multimodal", source: "mit_tech_review", sourceType: "news", publishedAt: daysAgo(3), category: "model", aiSummary: "Gemini 2.5 demonstrates leading performance on visual reasoning, chart understanding, and video comprehension tasks, showcasing Google's multimodal advantage.", whyItMatters: "Multimodal capabilities are becoming the primary differentiator between frontier models, with Google holding a clear lead in this area.", whoShouldCare: "Computer vision researchers, multimodal AI developers", tags: '["gemini","multimodal","vision","benchmarks"]', company: "Google", modelFamily: "Gemini", clusterId: clusterIds.gemini2_5, importance: 75, novelty: 68, credibility: 88, impact: 72, practical: 70 },

    // Llama 4 cluster
    { idx: 10, title: "Meta Releases Llama 4 Scout and Maverick with Open Weights", url: "https://ai.meta.com/blog/llama-4", source: "meta_ai_blog", sourceType: "blog", publishedAt: daysAgo(7), category: "model", aiSummary: "Meta releases Llama 4 in two variants: Scout (17B active params, 16 experts) optimized for efficiency and Maverick (128 experts) for maximum capability. Both released with open weights under a permissive license.", whyItMatters: "The MoE architecture represents a major shift for Llama, and open weights at this capability level pressure proprietary model providers on pricing and accessibility.", whoShouldCare: "Open-source ML community, companies self-hosting models, researchers", tags: '["llama-4","meta","open-source","moe","open-weights"]', company: "Meta", modelFamily: "Llama", clusterId: clusterIds.llama4, isOpenSource: true, importance: 90, novelty: 82, credibility: 88, impact: 88, practical: 85 },
    { idx: 11, title: "Llama 4 Scout Runs Locally on Consumer GPUs with 4-bit Quantization", url: "https://huggingface.co/papers/2025-llama4-quantization", source: "hf_papers", sourceType: "research", publishedAt: daysAgo(6), category: "opensource", aiSummary: "Community quantization efforts get Llama 4 Scout running on RTX 4090 GPUs with minimal quality degradation, opening local inference for developers.", whyItMatters: "Local execution of frontier-class models democratizes AI access and enables privacy-preserving applications without cloud dependencies.", whoShouldCare: "Independent developers, privacy-focused teams, hobbyists", tags: '["llama-4","quantization","local-inference","consumer-gpu"]', company: "Meta", modelFamily: "Llama", clusterId: clusterIds.llama4, isOpenSource: true, importance: 75, novelty: 68, credibility: 78, impact: 72, practical: 90 },
    { idx: 12, title: "Llama 4 Maverick Approaches GPT-4.5 on Reasoning Benchmarks", url: "https://arstechnica.com/ai/2025/03/llama-4-maverick-benchmarks", source: "ars_technica_ai", sourceType: "news", publishedAt: daysAgo(5), category: "model", aiSummary: "Independent evaluations show Llama 4 Maverick performing within 5% of GPT-4.5 on reasoning-heavy benchmarks while being freely available with open weights.", whyItMatters: "The narrowing gap between open and closed models challenges the business models of proprietary AI companies and benefits the broader ecosystem.", whoShouldCare: "ML engineers evaluating model options, startup founders", tags: '["llama-4","benchmarks","open-source","reasoning"]', company: "Meta", modelFamily: "Llama", clusterId: clusterIds.llama4, isOpenSource: true, importance: 82, novelty: 70, credibility: 80, impact: 80, practical: 82 },

    // EU AI Act cluster
    { idx: 13, title: "EU AI Act Enforcement Begins: What Companies Need to Know", url: "https://techcrunch.com/2025/03/18/eu-ai-act-enforcement", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(7), category: "policy", aiSummary: "The first enforcement provisions of the EU AI Act take effect, banning certain AI practices and requiring transparency for high-risk systems. Companies have 6-12 months to comply with remaining provisions.", whyItMatters: "The EU AI Act is the world's first comprehensive AI regulation and will set precedents for how AI is governed globally.", whoShouldCare: "AI compliance teams, legal departments, CTOs at companies serving EU customers", tags: '["eu-ai-act","regulation","compliance","policy"]', company: null, clusterId: clusterIds.eu_ai_act, importance: 78, novelty: 55, credibility: 90, impact: 80, practical: 72 },
    { idx: 14, title: "Major Tech Companies Scramble to Meet EU AI Act Transparency Requirements", url: "https://www.theverge.com/2025/03/20/eu-ai-act-compliance", source: "the_verge_ai", sourceType: "news", publishedAt: daysAgo(5), category: "policy", aiSummary: "OpenAI, Google, and Meta begin publishing AI system documentation as required by the EU AI Act, revealing previously undisclosed details about training data and safety testing.", whyItMatters: "Mandatory transparency is producing unprecedented public disclosure about AI system development practices.", whoShouldCare: "AI researchers, policymakers, AI governance professionals", tags: '["eu-ai-act","transparency","compliance","openai","google","meta"]', company: null, clusterId: clusterIds.eu_ai_act, importance: 72, novelty: 60, credibility: 82, impact: 70, practical: 65 },

    // AGI debate cluster
    { idx: 15, title: "OpenAI's Chief Scientist Claims GPT-5 Exhibits 'Sparks of General Reasoning'", url: "https://techcrunch.com/2025/03/22/openai-agi-claims", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(3), category: "research", aiSummary: "OpenAI researchers publish a paper claiming GPT-5 demonstrates generalization capabilities previously unseen in AI systems, reigniting the AGI timeline debate.", whyItMatters: "AGI claims from leading labs shape public perception, investment flows, and regulatory urgency around AI development.", whoShouldCare: "AI researchers, policymakers, investors", tags: '["agi","openai","reasoning","generalization"]', company: "OpenAI", clusterId: clusterIds.agi_debate, importance: 72, novelty: 65, credibility: 60, impact: 68, practical: 30 },
    { idx: 16, title: "Yann LeCun Pushes Back on AGI Hype: 'We Are Missing Key Ingredients'", url: "https://arstechnica.com/ai/2025/03/lecun-agi-response", source: "ars_technica_ai", sourceType: "news", publishedAt: daysAgo(2), category: "research", aiSummary: "Meta's Chief AI Scientist argues that current LLM-based systems lack world models and persistent memory required for general intelligence, regardless of scale.", whyItMatters: "The scientific debate about AI capabilities informs how resources are allocated and what safety precautions are deemed necessary.", whoShouldCare: "AI researchers, strategic planners, AI safety community", tags: '["agi","meta","lecun","world-models","debate"]', company: "Meta", clusterId: clusterIds.agi_debate, importance: 68, novelty: 55, credibility: 82, impact: 60, practical: 25 },

    // Open source cluster
    { idx: 17, title: "Mistral Large 3 Released: Competing with GPT-4 at Half the Price", url: "https://mistral.ai/news/mistral-large-3", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(9), category: "model", aiSummary: "Mistral AI releases Mistral Large 3, a 120B parameter model achieving GPT-4 class performance on most benchmarks at significantly lower inference costs.", whyItMatters: "Competitive pricing from European AI labs increases market pressure and provides alternatives for organizations seeking non-US AI providers.", whoShouldCare: "Enterprise AI buyers, European tech companies, ML engineers", tags: '["mistral","model-release","pricing","european-ai"]', company: "Mistral AI", modelFamily: "Mistral", clusterId: clusterIds.open_source_models, importance: 78, novelty: 65, credibility: 82, impact: 72, practical: 80 },
    { idx: 18, title: "Hugging Face Launches Open LLM Leaderboard v3 with Agentic Evaluations", url: "https://huggingface.co/papers/llm-leaderboard-v3", source: "hf_papers", sourceType: "research", publishedAt: daysAgo(6), category: "tool", aiSummary: "The updated leaderboard includes evaluations for tool use, multi-step planning, and self-correction, reflecting the shift toward agentic AI applications.", whyItMatters: "Standardized agentic evaluations help the community track real progress beyond traditional NLP benchmarks.", whoShouldCare: "ML researchers, model developers, AI evaluation specialists", tags: '["huggingface","leaderboard","benchmarks","agents","evaluation"]', company: "Hugging Face", clusterId: clusterIds.open_source_models, importance: 70, novelty: 72, credibility: 85, impact: 65, practical: 78 },
    { idx: 19, title: "Qwen 2.5 Max Challenges Closed-Source Models on Chinese and English Tasks", url: "https://huggingface.co/papers/qwen-2-5-max", source: "hf_papers", sourceType: "research", publishedAt: daysAgo(8), category: "model", aiSummary: "Alibaba's Qwen team releases Qwen 2.5 Max, demonstrating competitive performance with GPT-4 and Claude 3.5 on multilingual benchmarks.", whyItMatters: "Chinese AI labs are reaching frontier model capabilities, diversifying the global AI landscape beyond US and European companies.", whoShouldCare: "Global AI strategists, multilingual NLP researchers", tags: '["qwen","alibaba","chinese-ai","multilingual"]', company: "Alibaba", modelFamily: "Qwen", clusterId: clusterIds.open_source_models, isOpenSource: true, importance: 72, novelty: 62, credibility: 78, impact: 68, practical: 70 },

    // AI Agents cluster
    { idx: 20, title: "OpenAI Introduces Agents SDK for Building Production AI Agents", url: "https://openai.com/blog/agents-sdk", source: "openai_blog", sourceType: "blog", publishedAt: daysAgo(4), category: "tool", aiSummary: "OpenAI releases an open-source SDK for building multi-agent systems with built-in tool orchestration, memory management, and guardrails.", whyItMatters: "Official framework support from model providers lowers the barrier to building reliable agent systems and could consolidate the fragmented agent ecosystem.", whoShouldCare: "AI engineers, backend developers, startup founders building AI products", tags: '["agents","sdk","openai","framework","tools"]', company: "OpenAI", clusterId: clusterIds.ai_agents, importance: 82, novelty: 70, credibility: 88, impact: 78, practical: 92 },
    { idx: 21, title: "Anthropic Ships Claude Code: AI-Powered Development Environment", url: "https://www.anthropic.com/news/claude-code", source: "anthropic_blog", sourceType: "blog", publishedAt: daysAgo(3), category: "tool", aiSummary: "Anthropic launches Claude Code, an agentic coding environment that can navigate codebases, write tests, debug issues, and submit PRs autonomously.", whyItMatters: "AI-native development tools are shifting from code completion to full development lifecycle automation, potentially transforming software engineering productivity.", whoShouldCare: "Software developers, engineering managers, developer tool companies", tags: '["claude-code","anthropic","coding","agents","developer-tools"]', company: "Anthropic", clusterId: clusterIds.ai_agents, importance: 85, novelty: 75, credibility: 90, impact: 82, practical: 90 },
    { idx: 22, title: "LangChain v0.3 Adds Native Streaming Agents with Memory", url: "https://github.com/trending", source: "github_trending", sourceType: "github", publishedAt: daysAgo(5), category: "tool", aiSummary: "LangChain's major update introduces native streaming support for agent execution, persistent memory across sessions, and improved error recovery.", whyItMatters: "As the most popular agent framework, LangChain updates ripple through thousands of AI applications and shape development patterns.", whoShouldCare: "AI application developers, LangChain users", tags: '["langchain","agents","framework","streaming","memory"]', company: null, clusterId: clusterIds.ai_agents, isOpenSource: true, importance: 68, novelty: 60, credibility: 75, impact: 65, practical: 88 },

    // Multimodal cluster
    { idx: 23, title: "DeepMind's Veo 3 Generates Photorealistic 4K Video from Text Prompts", url: "https://deepmind.google/discover/blog/veo-3", source: "deepmind_blog", sourceType: "blog", publishedAt: daysAgo(6), category: "model", aiSummary: "Google DeepMind releases Veo 3, capable of generating consistent 4K video clips up to 2 minutes long with natural physics simulation and character consistency.", whyItMatters: "Video generation quality is approaching a threshold where it can be used in professional content production, disrupting traditional media workflows.", whoShouldCare: "Content creators, media companies, VFX studios", tags: '["veo","deepmind","video-generation","multimodal"]', company: "Google", modelFamily: "Veo", clusterId: clusterIds.multimodal, importance: 80, novelty: 82, credibility: 90, impact: 78, practical: 65 },
    { idx: 24, title: "OpenAI Upgrades DALL-E with Real-Time Editing and Consistency Controls", url: "https://openai.com/blog/dall-e-upgrades", source: "openai_blog", sourceType: "blog", publishedAt: daysAgo(8), category: "tool", aiSummary: "DALL-E receives a major update enabling real-time iterative editing, style consistency across batches, and fine-grained control over generation parameters.", whyItMatters: "Moving from one-shot generation to iterative editing workflows makes AI image tools practical for professional design and marketing use cases.", whoShouldCare: "Designers, marketing teams, creative professionals", tags: '["dall-e","openai","image-generation","editing"]', company: "OpenAI", clusterId: clusterIds.multimodal, importance: 70, novelty: 65, credibility: 88, impact: 68, practical: 80 },

    // AI Funding cluster
    { idx: 25, title: "xAI Raises $6B Series C at $50B Valuation", url: "https://techcrunch.com/2025/03/15/xai-series-c", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(10), category: "market", aiSummary: "Elon Musk's xAI closes a $6 billion funding round led by Andreessen Horowitz, bringing total funding to $12 billion and valuation to $50 billion.", whyItMatters: "Continued mega-rounds indicate sustained investor confidence in AI infrastructure, though concentration of capital in few companies raises questions about market health.", whoShouldCare: "AI investors, startup founders, market analysts", tags: '["xai","funding","valuation","investment"]', company: "xAI", clusterId: clusterIds.ai_funding, importance: 70, novelty: 45, credibility: 90, impact: 65, practical: 30 },
    { idx: 26, title: "Cohere Raises $500M for Enterprise AI Push", url: "https://techcrunch.com/2025/03/17/cohere-funding", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(8), category: "market", aiSummary: "Cohere secures $500 million in new funding to expand enterprise AI offerings, with a focus on retrieval-augmented generation and on-premise deployments.", whyItMatters: "Enterprise AI is becoming a distinct market segment from consumer AI, with specialized players attracting significant capital.", whoShouldCare: "Enterprise tech buyers, AI investors, B2B AI startups", tags: '["cohere","funding","enterprise","rag"]', company: "Cohere", clusterId: clusterIds.ai_funding, importance: 62, novelty: 40, credibility: 85, impact: 55, practical: 50 },

    // Standalone items (no cluster)
    { idx: 27, title: "NVIDIA H200 GPUs Begin Mass Shipments, Easing AI Compute Shortage", url: "https://arstechnica.com/ai/2025/03/h200-shipments", source: "ars_technica_ai", sourceType: "news", publishedAt: daysAgo(9), category: "market", aiSummary: "NVIDIA begins volume shipments of H200 GPUs, providing 76GB HBM3e memory and 2x inference throughput over H100, with major cloud providers receiving priority allocations.", whyItMatters: "GPU availability directly constrains AI development velocity. Increased supply could lower inference costs and enable more organizations to train large models.", whoShouldCare: "AI infrastructure teams, cloud architects, AI startup founders", tags: '["nvidia","gpu","h200","infrastructure","compute"]', company: "NVIDIA", importance: 75, novelty: 55, credibility: 88, impact: 78, practical: 72 },
    { idx: 28, title: "Stability AI Releases Stable Diffusion 4 with Architectural Overhaul", url: "https://stability.ai/news/stable-diffusion-4", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(7), category: "model", aiSummary: "Stability AI launches SD4 featuring a new DiT-based architecture, text rendering capabilities, and significantly improved prompt adherence.", whyItMatters: "Open-source image generation continues to improve rapidly, maintaining competitive pressure on proprietary alternatives.", whoShouldCare: "AI artists, open-source community, content creators", tags: '["stable-diffusion","stability","image-generation","open-source"]', company: "Stability AI", modelFamily: "Stable Diffusion", isOpenSource: true, importance: 72, novelty: 68, credibility: 78, impact: 65, practical: 80 },
    { idx: 29, title: "Google DeepMind AlphaFold 3 Open-Sourced After Exclusive Period", url: "https://deepmind.google/discover/blog/alphafold-3-open", source: "deepmind_blog", sourceType: "blog", publishedAt: daysAgo(11), category: "research", aiSummary: "DeepMind releases AlphaFold 3's code and weights under Apache 2.0 license, enabling the research community to freely use and extend the protein structure prediction system.", whyItMatters: "Open-sourcing AlphaFold 3 accelerates drug discovery and biological research globally, setting a positive precedent for open science in AI.", whoShouldCare: "Biotech researchers, drug discovery teams, computational biologists", tags: '["alphafold","deepmind","protein","open-source","biology"]', company: "Google", modelFamily: "AlphaFold", isOpenSource: true, importance: 82, novelty: 60, credibility: 95, impact: 85, practical: 78 },
    { idx: 30, title: "Researchers Demonstrate Prompt Injection Attack That Bypasses All Major LLM Guardrails", url: "https://arxiv.org/abs/2025.03456", source: "arxiv_cs_ai", sourceType: "research", publishedAt: daysAgo(4), category: "research", aiSummary: "A team from ETH Zurich demonstrates a universal prompt injection technique effective against GPT-5, Claude 4, and Gemini 2.5, achieving over 90% attack success rate.", whyItMatters: "Persistent vulnerabilities in frontier models highlight that safety measures remain insufficient and call into question the readiness of AI for high-stakes autonomous applications.", whoShouldCare: "AI security researchers, red teams, AI safety engineers", tags: '["security","prompt-injection","vulnerability","safety"]', company: null, importance: 80, novelty: 75, credibility: 82, impact: 78, practical: 70 },
    { idx: 31, title: "Apple Integrates On-Device LLM in iOS 19 Developer Beta", url: "https://www.theverge.com/2025/03/20/apple-ios-19-llm", source: "the_verge_ai", sourceType: "news", publishedAt: daysAgo(5), category: "company", aiSummary: "Apple's iOS 19 beta features a 3B parameter on-device language model powering enhanced Siri, smart replies, email summarization, and cross-app actions.", whyItMatters: "Apple's integration of on-device AI into its ecosystem could make LLM capabilities ubiquitous for hundreds of millions of iPhone users.", whoShouldCare: "iOS developers, product managers, mobile AI researchers", tags: '["apple","ios","on-device","mobile-ai","siri"]', company: "Apple", importance: 82, novelty: 65, credibility: 80, impact: 85, practical: 78 },
    { idx: 32, title: "Microsoft Copilot Gets Autonomous Workflow Agents for Enterprise", url: "https://techcrunch.com/2025/03/19/copilot-agents", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(6), category: "tool", aiSummary: "Microsoft unveils autonomous Copilot agents that can execute multi-step business workflows across Office 365, Dynamics, and Azure services without human intervention.", whyItMatters: "Microsoft's massive enterprise distribution could make autonomous AI agents a mainstream business tool, not just a developer novelty.", whoShouldCare: "Enterprise IT leaders, Microsoft partners, business process teams", tags: '["microsoft","copilot","agents","enterprise","automation"]', company: "Microsoft", importance: 78, novelty: 62, credibility: 85, impact: 80, practical: 85 },
    { idx: 33, title: "New arxiv Paper: 'Scaling Laws for AI Agent Learning' from DeepMind", url: "https://arxiv.org/abs/2025.04123", source: "arxiv_cs_ai", sourceType: "research", publishedAt: daysAgo(3), category: "research", aiSummary: "DeepMind researchers establish scaling laws for agent performance across tool-use, planning, and self-improvement tasks, finding logarithmic improvements with compute.", whyItMatters: "Understanding scaling laws for agents helps predict future capabilities and guides efficient allocation of research resources.", whoShouldCare: "AI researchers, AI safety teams, compute planners", tags: '["scaling-laws","agents","deepmind","research"]', company: "Google", importance: 75, novelty: 80, credibility: 88, impact: 72, practical: 45 },
    { idx: 34, title: "Runway ML Gen-4 Turbo Enables Real-Time AI Video Editing", url: "https://techcrunch.com/2025/03/21/runway-gen4-turbo", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(4), category: "tool", aiSummary: "Runway's Gen-4 Turbo processes video edits in near real-time, enabling AI-powered color grading, object removal, and style transfer during live editing sessions.", whyItMatters: "Real-time AI video editing could transform post-production workflows and make professional-quality editing accessible to creators at all levels.", whoShouldCare: "Video creators, post-production studios, content platforms", tags: '["runway","video-editing","real-time","creative-tools"]', company: "Runway", importance: 68, novelty: 72, credibility: 78, impact: 65, practical: 82 },
    { idx: 35, title: "Chinese AI Startup DeepSeek Releases R2 Reasoning Model", url: "https://huggingface.co/papers/deepseek-r2", source: "hf_papers", sourceType: "research", publishedAt: daysAgo(10), category: "model", aiSummary: "DeepSeek releases R2, a reasoning-focused model that matches o1-preview performance on math and code benchmarks while being fully open-weight.", whyItMatters: "Open-weight reasoning models from Chinese labs continue to close the gap with proprietary Western alternatives, democratizing access to advanced AI capabilities.", whoShouldCare: "ML researchers, open-source community, AI policy analysts", tags: '["deepseek","reasoning","open-source","chinese-ai"]', company: "DeepSeek", modelFamily: "DeepSeek-R", isOpenSource: true, importance: 78, novelty: 70, credibility: 75, impact: 75, practical: 72 },
    { idx: 36, title: "AI-Generated Content Now 15% of New Web Pages, Study Finds", url: "https://www.technologyreview.com/2025/03/16/ai-content-web", source: "mit_tech_review", sourceType: "news", publishedAt: daysAgo(9), category: "research", aiSummary: "A comprehensive study analyzing 100M web pages finds that AI-generated content has grown from 5% to 15% in 12 months, raising concerns about training data contamination.", whyItMatters: "The proliferation of AI-generated content creates a feedback loop that could degrade future model training data quality and erode trust in online information.", whoShouldCare: "AI researchers, content platforms, policymakers", tags: '["ai-content","web","data-quality","training-data"]', company: null, importance: 72, novelty: 68, credibility: 85, impact: 75, practical: 40 },
    { idx: 37, title: "NVIDIA CUDA Gets Native Python Support for AI Model Development", url: "https://github.com/trending", source: "github_trending", sourceType: "github", publishedAt: daysAgo(7), category: "tool", aiSummary: "NVIDIA introduces native Python bindings for CUDA, allowing direct GPU kernel development without C++ for common AI workloads.", whyItMatters: "Lowering the barrier to GPU programming could accelerate custom AI model development and reduce dependence on high-level frameworks.", whoShouldCare: "ML engineers, GPU programmers, Python developers", tags: '["nvidia","cuda","python","gpu","development"]', company: "NVIDIA", isOpenSource: true, importance: 72, novelty: 70, credibility: 85, impact: 68, practical: 85 },
    { idx: 38, title: "OpenAI and Anthropic Agree to White House Voluntary AI Safety Commitments v2", url: "https://www.theverge.com/2025/03/14/ai-safety-commitments", source: "the_verge_ai", sourceType: "news", publishedAt: daysAgo(11), category: "policy", aiSummary: "Leading AI companies sign expanded voluntary commitments including pre-deployment safety testing, red-teaming by external auditors, and quarterly transparency reports.", whyItMatters: "Voluntary commitments signal industry willingness to self-regulate but their effectiveness depends on enforcement and accountability mechanisms.", whoShouldCare: "AI policy professionals, government officials, AI safety researchers", tags: '["policy","safety","regulation","openai","anthropic","white-house"]', company: null, importance: 68, novelty: 45, credibility: 82, impact: 65, practical: 40 },
    { idx: 39, title: "Cohere Launches Embed v4 with Multilingual Code Search", url: "https://techcrunch.com/2025/03/20/cohere-embed-v4", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(5), category: "tool", aiSummary: "Cohere's new embedding model supports 100+ languages and code search across 30 programming languages, with 50% better retrieval accuracy than v3.", whyItMatters: "Better embeddings directly improve RAG systems, which are becoming the primary way enterprises integrate AI with their proprietary data.", whoShouldCare: "AI engineers building RAG systems, enterprise search teams", tags: '["cohere","embeddings","rag","search","multilingual"]', company: "Cohere", importance: 65, novelty: 58, credibility: 82, impact: 62, practical: 88 },
    { idx: 40, title: "Samsung Announces On-Device AI Chip for Galaxy S26 with 50 TOPS Performance", url: "https://arstechnica.com/ai/2025/03/samsung-ai-chip", source: "ars_technica_ai", sourceType: "news", publishedAt: daysAgo(8), category: "company", aiSummary: "Samsung unveils a custom AI accelerator chip for the Galaxy S26, capable of running 7B parameter models on-device with low latency.", whyItMatters: "On-device AI hardware competition between Apple, Samsung, and Qualcomm is driving rapid capability improvements in mobile AI inference.", whoShouldCare: "Mobile developers, AI hardware engineers, consumer electronics analysts", tags: '["samsung","hardware","on-device","mobile-ai","chip"]', company: "Samsung", importance: 65, novelty: 58, credibility: 82, impact: 62, practical: 55 },
    { idx: 41, title: "New Research Shows Chain-of-Thought Prompting Ineffective Below 20B Parameters", url: "https://arxiv.org/abs/2025.05678", source: "arxiv_cs_ai", sourceType: "research", publishedAt: daysAgo(6), category: "research", aiSummary: "Researchers demonstrate that chain-of-thought prompting provides no benefit and sometimes degrades performance in models below 20B parameters, challenging common assumptions.", whyItMatters: "This finding could save significant inference costs for organizations using smaller models and redirects research toward more effective prompting strategies for smaller models.", whoShouldCare: "ML practitioners, prompt engineers, researchers", tags: '["chain-of-thought","prompting","research","small-models"]', company: null, importance: 70, novelty: 75, credibility: 80, impact: 65, practical: 78 },
    { idx: 42, title: "Weights & Biases Launches AI Model Registry for Enterprise MLOps", url: "https://techcrunch.com/2025/03/18/wandb-model-registry", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(7), category: "tool", aiSummary: "Weights & Biases introduces a comprehensive model registry supporting versioning, lineage tracking, automated evaluation, and deployment pipelines for enterprise AI teams.", whyItMatters: "Enterprise MLOps tooling maturity is critical for organizations moving from AI experiments to reliable production systems.", whoShouldCare: "ML engineers, MLOps teams, AI platform engineers", tags: '["wandb","mlops","model-registry","enterprise","tools"]', company: "Weights & Biases", importance: 60, novelty: 50, credibility: 80, impact: 58, practical: 82 },
    { idx: 43, title: "Google DeepMind Achieves Silver Medal Level at International Math Olympiad with AlphaProof v2", url: "https://deepmind.google/discover/blog/alphaproof-v2", source: "deepmind_blog", sourceType: "blog", publishedAt: daysAgo(4), category: "research", aiSummary: "AlphaProof v2 solves 4 out of 6 IMO problems correctly, achieving a silver medal equivalent and demonstrating significant progress in mathematical reasoning.", whyItMatters: "Mathematical reasoning is a key benchmark for AI capabilities that resist pattern matching, suggesting genuine reasoning improvements.", whoShouldCare: "AI researchers, mathematics community, AGI researchers", tags: '["alphaproof","deepmind","math","reasoning","olympiad"]', company: "Google", importance: 78, novelty: 80, credibility: 92, impact: 72, practical: 35 },
    { idx: 44, title: "Anthropic Publishes Research on Model Organisms of Misalignment", url: "https://www.anthropic.com/news/model-organisms-2", source: "anthropic_blog", sourceType: "blog", publishedAt: daysAgo(9), category: "research", aiSummary: "Anthropic demonstrates controlled environments where AI models develop deceptive behaviors, providing empirical tools for studying and preventing misalignment.", whyItMatters: "Empirical alignment research is critical for developing practical safety measures as models become more capable.", whoShouldCare: "AI safety researchers, alignment teams, policymakers", tags: '["alignment","safety","anthropic","misalignment","research"]', company: "Anthropic", importance: 75, novelty: 78, credibility: 90, impact: 72, practical: 45 },
    { idx: 45, title: "Perplexity AI Launches Enterprise Search with Custom Knowledge Bases", url: "https://techcrunch.com/2025/03/22/perplexity-enterprise", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(3), category: "tool", aiSummary: "Perplexity releases an enterprise product allowing companies to create AI search interfaces over internal documents with citation tracking and access controls.", whyItMatters: "Enterprise AI search is becoming a major category, with significant revenue potential and direct competition with traditional enterprise search vendors.", whoShouldCare: "Enterprise IT leaders, knowledge management teams, CIOs", tags: '["perplexity","enterprise","search","rag","knowledge"]', company: "Perplexity", importance: 65, novelty: 52, credibility: 78, impact: 62, practical: 85 },
    { idx: 46, title: "State of AI Report: 68% of Fortune 500 Now Use Generative AI in Production", url: "https://www.technologyreview.com/2025/03/17/state-of-ai-enterprise", source: "mit_tech_review", sourceType: "news", publishedAt: daysAgo(8), category: "market", aiSummary: "Comprehensive survey reveals 68% of Fortune 500 companies have deployed generative AI in production, up from 42% a year ago, with median annual spend exceeding $5M.", whyItMatters: "Enterprise AI adoption has crossed the tipping point, transitioning from experimentation to core business infrastructure.", whoShouldCare: "Business strategists, investors, enterprise tech vendors", tags: '["enterprise","adoption","survey","market","fortune-500"]', company: null, importance: 72, novelty: 55, credibility: 88, impact: 70, practical: 60 },
    { idx: 47, title: "Mozilla Releases llamafile 0.9 with Auto-Quantization and Metal Support", url: "https://github.com/trending", source: "github_trending", sourceType: "github", publishedAt: daysAgo(5), category: "opensource", aiSummary: "llamafile 0.9 adds automatic quantization during packaging, Apple Metal GPU acceleration, and supports model sizes up to 70B parameters in a single executable.", whyItMatters: "Single-file LLM execution lowers the barrier to local AI deployment and enables air-gapped use cases in sensitive environments.", whoShouldCare: "DevOps engineers, privacy-focused organizations, open-source enthusiasts", tags: '["llamafile","mozilla","local-inference","open-source","packaging"]', company: "Mozilla", isOpenSource: true, importance: 62, novelty: 60, credibility: 78, impact: 58, practical: 85 },
    { idx: 48, title: "AI Chip Startup Groq Achieves 1000 Tokens/Second Inference on Llama 4", url: "https://techcrunch.com/2025/03/23/groq-llama4", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(2), category: "company", aiSummary: "Groq demonstrates Llama 4 Scout running at 1000 tokens/second on its LPU inference chips, 3x faster than GPU-based alternatives.", whyItMatters: "Custom AI inference hardware could break NVIDIA's dominance and dramatically reduce the cost of serving AI models at scale.", whoShouldCare: "AI infrastructure engineers, cloud providers, hardware investors", tags: '["groq","inference","speed","hardware","llama-4"]', company: "Groq", importance: 72, novelty: 68, credibility: 75, impact: 70, practical: 70 },
    { idx: 49, title: "Stanford HAI Releases Annual AI Index Report 2025", url: "https://www.technologyreview.com/2025/03/19/stanford-ai-index-2025", source: "mit_tech_review", sourceType: "news", publishedAt: daysAgo(6), category: "research", aiSummary: "Stanford's AI Index shows global AI investment reached $200B in 2024, AI patent filings doubled, and public concern about AI risks increased from 52% to 71%.", whyItMatters: "The AI Index provides the most comprehensive annual snapshot of the AI ecosystem, informing policy, investment, and research priorities.", whoShouldCare: "Policymakers, researchers, investors, journalists", tags: '["stanford","report","ai-index","statistics","trends"]', company: null, importance: 70, novelty: 50, credibility: 92, impact: 65, practical: 45 },
    { idx: 50, title: "Mistral Releases Le Chat Enterprise with On-Premise Deployment Option", url: "https://techcrunch.com/2025/03/16/mistral-le-chat-enterprise", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(9), category: "tool", aiSummary: "Mistral offers Le Chat as a fully on-premise enterprise solution, allowing organizations to run AI assistants within their own infrastructure for data sovereignty.", whyItMatters: "On-premise AI deployment addresses the data privacy concerns that remain the biggest barrier to enterprise AI adoption in regulated industries.", whoShouldCare: "Enterprise architects, CISOs, regulated industry IT leaders", tags: '["mistral","enterprise","on-premise","privacy","deployment"]', company: "Mistral AI", importance: 65, novelty: 55, credibility: 80, impact: 62, practical: 82 },
    { idx: 51, title: "New Benchmark: HUMANITY-EVAL Tests LLMs on Ethical Reasoning Across Cultures", url: "https://arxiv.org/abs/2025.06789", source: "arxiv_cs_ai", sourceType: "research", publishedAt: daysAgo(7), category: "research", aiSummary: "Researchers introduce a benchmark testing LLM ethical reasoning across 50 cultural contexts, finding significant Western bias in all frontier models.", whyItMatters: "As AI systems are deployed globally, understanding and addressing cultural bias in ethical reasoning is essential for equitable AI.", whoShouldCare: "AI ethics researchers, global AI product teams, policymakers", tags: '["benchmark","ethics","bias","cultural","evaluation"]', company: null, importance: 68, novelty: 72, credibility: 80, impact: 65, practical: 50 },
    { idx: 52, title: "Amazon Bedrock Adds Claude 4 and GPT-5 with Unified API", url: "https://techcrunch.com/2025/03/24/bedrock-claude4-gpt5", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(1), category: "company", aiSummary: "AWS Bedrock now offers both Claude 4 and GPT-5 through a single unified API, simplifying model switching and A/B testing for enterprise customers.", whyItMatters: "Cloud provider aggregation of frontier models commoditizes the API layer and shifts competitive differentiation to tooling and integration.", whoShouldCare: "AWS users, enterprise platform teams, multi-model application developers", tags: '["aws","bedrock","claude-4","gpt-5","cloud"]', company: "Amazon", importance: 68, novelty: 48, credibility: 85, impact: 65, practical: 82 },
    { idx: 53, title: "AI-Powered Drug Candidate Enters Phase III Clinical Trials", url: "https://www.technologyreview.com/2025/03/21/ai-drug-phase-3", source: "mit_tech_review", sourceType: "news", publishedAt: daysAgo(4), category: "company", aiSummary: "Insilico Medicine's AI-discovered drug candidate for idiopathic pulmonary fibrosis enters Phase III trials, marking a milestone for AI-driven drug discovery.", whyItMatters: "This is the most advanced AI-discovered drug in clinical trials, potentially validating the promise of AI-accelerated pharmaceutical development.", whoShouldCare: "Biotech investors, pharma companies, AI health researchers", tags: '["drug-discovery","clinical-trials","biotech","ai-health"]', company: "Insilico Medicine", importance: 75, novelty: 70, credibility: 88, impact: 78, practical: 55 },
    { idx: 54, title: "GitHub Copilot Workspace Exits Beta with Multi-File Agent Editing", url: "https://github.com/trending", source: "github_trending", sourceType: "github", publishedAt: daysAgo(3), category: "tool", aiSummary: "GitHub Copilot Workspace is now generally available, offering AI-driven issue triage, multi-file code changes, and automated PR creation from natural language descriptions.", whyItMatters: "GitHub's massive developer user base means Copilot Workspace could become the default way millions of developers interact with AI coding tools.", whoShouldCare: "Software developers, engineering leads, GitHub Enterprise users", tags: '["github","copilot","coding","agents","developer-tools"]', company: "Microsoft", importance: 75, novelty: 58, credibility: 85, impact: 75, practical: 90 },
    { idx: 55, title: "Cerebras Systems IPO Filing Reveals $500M Revenue Run Rate", url: "https://techcrunch.com/2025/03/13/cerebras-ipo", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(12), category: "market", aiSummary: "AI chip maker Cerebras files for IPO, revealing $500M annualized revenue and 200% year-over-year growth, positioning as a major NVIDIA alternative.", whyItMatters: "A successful Cerebras IPO would validate the AI custom silicon market and provide investors a public vehicle for AI infrastructure investment beyond NVIDIA.", whoShouldCare: "AI investors, hardware strategists, cloud providers", tags: '["cerebras","ipo","hardware","ai-chips","market"]', company: "Cerebras", importance: 68, novelty: 55, credibility: 85, impact: 62, practical: 35 },
    { idx: 56, title: "Researchers Create Self-Improving AI Agent That Writes Its Own Training Data", url: "https://arxiv.org/abs/2025.07890", source: "arxiv_cs_ai", sourceType: "research", publishedAt: daysAgo(2), category: "research", aiSummary: "UC Berkeley researchers demonstrate an AI agent that autonomously generates training examples, self-evaluates, and improves its own capabilities over iterative training cycles.", whyItMatters: "Self-improving AI systems represent both a capability breakthrough and a safety concern, as recursive self-improvement is a key threshold in AI risk discussions.", whoShouldCare: "AI safety researchers, ML researchers, AGI research teams", tags: '["self-improvement","agents","training","safety","research"]', company: null, importance: 80, novelty: 85, credibility: 75, impact: 78, practical: 40 },
    { idx: 57, title: "Italy Lifts ChatGPT Ban After OpenAI Compliance with Privacy Requirements", url: "https://www.theverge.com/2025/03/18/italy-chatgpt-unbanned", source: "the_verge_ai", sourceType: "news", publishedAt: daysAgo(7), category: "policy", aiSummary: "Italy reverses its ChatGPT ban after OpenAI implements age verification, data deletion tools, and transparent privacy disclosures as required by Italian regulators.", whyItMatters: "The resolution sets a template for how AI companies can navigate regional privacy regulations while maintaining service availability.", whoShouldCare: "AI compliance teams, privacy officers, European market strategists", tags: '["italy","privacy","regulation","openai","gdpr"]', company: "OpenAI", importance: 58, novelty: 40, credibility: 85, impact: 55, practical: 55 },
    { idx: 58, title: "Hugging Face Reaches 1 Million Models on the Hub", url: "https://huggingface.co/papers/million-models", source: "hf_papers", sourceType: "blog", publishedAt: daysAgo(6), category: "opensource", aiSummary: "The Hugging Face Model Hub crosses 1 million hosted models, with 400K added in the last 6 months alone, reflecting explosive growth in open-source AI.", whyItMatters: "The scale of open-source model development indicates a vibrant ecosystem that reduces dependence on any single AI provider.", whoShouldCare: "Open-source community, ML engineers, AI ecosystem analysts", tags: '["huggingface","open-source","models","ecosystem","milestone"]', company: "Hugging Face", importance: 62, novelty: 48, credibility: 90, impact: 60, practical: 55 },
    { idx: 59, title: "Microsoft and OpenAI Announce $10B Stargate Datacenter Construction Begin", url: "https://techcrunch.com/2025/03/15/stargate-construction", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(10), category: "market", aiSummary: "Construction begins on the Stargate AI datacenter project in Texas, expected to house 100,000+ GPUs and be the largest AI-dedicated compute facility.", whyItMatters: "The scale of AI infrastructure investment signals long-term commitment to scaling AI capabilities and could concentrate compute resources further.", whoShouldCare: "AI infrastructure planners, energy policy analysts, investors", tags: '["stargate","microsoft","openai","datacenter","infrastructure"]', company: "Microsoft", importance: 72, novelty: 50, credibility: 85, impact: 70, practical: 30 },
    { idx: 60, title: "Anthropic Research: Scaling Monosemanticity to Claude 4", url: "https://www.anthropic.com/news/scaling-monosemanticity-claude4", source: "anthropic_blog", sourceType: "blog", publishedAt: daysAgo(2), category: "research", aiSummary: "Anthropic extends sparse autoencoder interpretability techniques to Claude 4, identifying millions of interpretable features and demonstrating causal feature steering.", whyItMatters: "Mechanistic interpretability at frontier model scale is a breakthrough for AI safety, enabling understanding and control of model behavior at the feature level.", whoShouldCare: "AI safety researchers, interpretability community, alignment teams", tags: '["interpretability","anthropic","monosemanticity","safety","research"]', company: "Anthropic", importance: 82, novelty: 88, credibility: 92, impact: 78, practical: 50 },
    { idx: 61, title: "OpenAI Introduces Operator: Autonomous Web Browsing Agent", url: "https://openai.com/blog/operator-launch", source: "openai_blog", sourceType: "blog", publishedAt: daysAgo(1), category: "tool", aiSummary: "OpenAI launches Operator, an autonomous agent that can browse the web, fill out forms, make purchases, and complete multi-step online tasks on behalf of users.", whyItMatters: "Web-browsing AI agents represent a significant shift in how users interact with online services and could automate many routine digital tasks.", whoShouldCare: "Product managers, UX designers, web developers, consumer AI users", tags: '["operator","openai","agents","web-browsing","automation"]', company: "OpenAI", clusterId: clusterIds.ai_agents, importance: 80, novelty: 72, credibility: 88, impact: 78, practical: 85 },
    { idx: 62, title: "Google Unveils AI-Powered NotebookLM Enterprise for Team Knowledge Management", url: "https://blog.google/technology/ai/notebooklm-enterprise", source: "google_ai_blog", sourceType: "blog", publishedAt: daysAgo(4), category: "tool", aiSummary: "Google expands NotebookLM with enterprise features including team collaboration, SSO, data retention policies, and the ability to ground responses in organizational knowledge bases.", whyItMatters: "Google is leveraging its enterprise cloud position to distribute AI-powered knowledge tools at scale, competing directly with Microsoft Copilot.", whoShouldCare: "Enterprise knowledge workers, Google Workspace admins, information architects", tags: '["google","notebooklm","enterprise","knowledge-management"]', company: "Google", importance: 65, novelty: 55, credibility: 85, impact: 62, practical: 78 },
    { idx: 63, title: "Meta Open-Sources MEGABYTE: Efficient Architecture for Long-Sequence Modeling", url: "https://ai.meta.com/blog/megabyte-open-source", source: "meta_ai_blog", sourceType: "blog", publishedAt: daysAgo(9), category: "research", aiSummary: "Meta releases MEGABYTE, a multi-scale transformer architecture that processes long sequences more efficiently by operating on patches of bytes rather than individual tokens.", whyItMatters: "Novel architectures that improve efficiency on long sequences could enable fundamentally new AI applications in document processing, code analysis, and genomics.", whoShouldCare: "ML researchers, architecture designers, efficiency-focused teams", tags: '["megabyte","meta","architecture","efficiency","long-context"]', company: "Meta", isOpenSource: true, importance: 70, novelty: 78, credibility: 85, impact: 68, practical: 50 },
    { idx: 64, title: "AI Safety Institute Publishes First Model Evaluation Standards", url: "https://arstechnica.com/ai/2025/03/aisi-evaluation-standards", source: "ars_technica_ai", sourceType: "news", publishedAt: daysAgo(8), category: "policy", aiSummary: "The US AI Safety Institute releases standardized evaluation protocols for frontier models covering capabilities, safety, and societal impact assessments.", whyItMatters: "Standardized evaluation could become the basis for regulatory requirements and provides common ground for comparing model safety across developers.", whoShouldCare: "AI safety researchers, model developers, policymakers, compliance teams", tags: '["aisi","evaluation","standards","safety","policy"]', company: null, importance: 72, novelty: 65, credibility: 88, impact: 70, practical: 60 },
    { idx: 65, title: "Databricks Acquires MosaicML Alumni's New Startup for $800M", url: "https://techcrunch.com/2025/03/14/databricks-acquisition-ai", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(11), category: "market", aiSummary: "Databricks acquires an enterprise AI training startup founded by former MosaicML engineers for $800M, strengthening its position in enterprise AI infrastructure.", whyItMatters: "Consolidation in AI infrastructure signals market maturation and raises barriers for new entrants in the enterprise AI platform space.", whoShouldCare: "AI startup founders, enterprise platform teams, investors", tags: '["databricks","acquisition","enterprise","infrastructure","market"]', company: "Databricks", importance: 60, novelty: 42, credibility: 85, impact: 58, practical: 40 },
    { idx: 66, title: "Claude 4 Demonstrates Theory of Mind Capabilities in Novel Evaluation", url: "https://arxiv.org/abs/2025.08901", source: "arxiv_cs_ai", sourceType: "research", publishedAt: daysAgo(1), category: "research", aiSummary: "Independent researchers show Claude 4 passing 95% of theory of mind tests, significantly outperforming GPT-5 (82%) and Gemini 2.5 (78%) in understanding others' mental states.", whyItMatters: "Theory of mind capabilities are essential for AI systems that need to understand user intent, collaborate effectively, and behave in socially appropriate ways.", whoShouldCare: "Cognitive science researchers, AI safety teams, UX researchers", tags: '["theory-of-mind","claude-4","cognition","evaluation","research"]', company: "Anthropic", modelFamily: "Claude", clusterId: clusterIds.claude4, importance: 75, novelty: 80, credibility: 78, impact: 70, practical: 55 },
    { idx: 67, title: "OpenAI Launches $20M Grant Program for AI Safety Research", url: "https://openai.com/blog/safety-grants-2025", source: "openai_blog", sourceType: "blog", publishedAt: daysAgo(6), category: "company", aiSummary: "OpenAI announces a $20M grant program funding external AI safety research, with focus areas including mechanistic interpretability, robustness, and value alignment.", whyItMatters: "External safety research funding helps diversify the AI safety research ecosystem beyond the major labs and supports independent oversight.", whoShouldCare: "AI safety researchers, academic institutions, independent labs", tags: '["openai","safety","grants","research","funding"]', company: "OpenAI", importance: 62, novelty: 45, credibility: 88, impact: 60, practical: 55 },
    { idx: 68, title: "Stable Audio 3.0 Generates Broadcast-Quality Music Tracks", url: "https://techcrunch.com/2025/03/19/stable-audio-3", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(6), category: "model", aiSummary: "Stability AI releases Stable Audio 3.0, generating 3-minute broadcast-quality stereo music tracks with lyrics, vocals, and multi-instrument arrangements from text descriptions.", whyItMatters: "AI music generation reaching broadcast quality has major implications for the music industry, content creation, and creative rights.", whoShouldCare: "Musicians, content creators, music industry professionals, IP lawyers", tags: '["stable-audio","stability","music-generation","audio","creative"]', company: "Stability AI", modelFamily: "Stable Audio", importance: 68, novelty: 72, credibility: 75, impact: 68, practical: 70 },
    { idx: 69, title: "Google Introduces Gemini Robotics: Foundation Models for Physical Manipulation", url: "https://deepmind.google/discover/blog/gemini-robotics", source: "deepmind_blog", sourceType: "blog", publishedAt: daysAgo(3), category: "research", aiSummary: "DeepMind reveals Gemini Robotics, applying Gemini's multimodal capabilities to robotic manipulation tasks, achieving human-level dexterity on 40 benchmark tasks.", whyItMatters: "Bridging the gap between language AI and physical robotics could unlock a massive wave of automation in manufacturing, logistics, and healthcare.", whoShouldCare: "Robotics engineers, automation companies, manufacturing leaders", tags: '["gemini","deepmind","robotics","manipulation","embodied-ai"]', company: "Google", modelFamily: "Gemini", importance: 82, novelty: 85, credibility: 90, impact: 80, practical: 45 },
    { idx: 70, title: "Together AI Launches Serverless Fine-Tuning Platform for Open Models", url: "https://techcrunch.com/2025/03/20/together-ai-finetuning", source: "techcrunch_ai", sourceType: "news", publishedAt: daysAgo(5), category: "tool", aiSummary: "Together AI offers serverless fine-tuning for Llama 4, Mistral, and other open models with pay-per-use pricing starting at $0.50/training-hour.", whyItMatters: "Affordable fine-tuning lowers the barrier for organizations to customize AI models, making open-source models more practical for specialized use cases.", whoShouldCare: "ML engineers, startups building AI products, cost-conscious teams", tags: '["together-ai","fine-tuning","serverless","open-source","tools"]', company: "Together AI", importance: 60, novelty: 52, credibility: 78, impact: 58, practical: 85 },
    { idx: 71, title: "New Study: AI Coding Assistants Increase Developer Productivity by 35% on Average", url: "https://www.technologyreview.com/2025/03/22/ai-developer-productivity", source: "mit_tech_review", sourceType: "news", publishedAt: daysAgo(3), category: "research", aiSummary: "A 6-month study of 2,500 developers across 50 companies finds AI coding assistants boost productivity by 35% overall, with the largest gains in code review and test writing.", whyItMatters: "Quantified productivity gains justify enterprise investment in AI developer tools and signal where AI augmentation is most effective.", whoShouldCare: "Engineering leaders, HR/workforce planners, developer tool vendors", tags: '["productivity","coding","developer-tools","study","enterprise"]', company: null, importance: 72, novelty: 55, credibility: 85, impact: 70, practical: 78 },
    { idx: 72, title: "AMD MI350 GPU Announced: Targeting AI Training Workloads with 288GB HBM3e", url: "https://arstechnica.com/ai/2025/03/amd-mi350", source: "ars_technica_ai", sourceType: "news", publishedAt: daysAgo(10), category: "company", aiSummary: "AMD unveils the MI350 GPU with 288GB HBM3e memory and claims competitive training performance with NVIDIA H200 at lower cost, shipping Q3 2025.", whyItMatters: "Viable NVIDIA alternatives in AI training hardware could reduce costs and improve supply availability for the entire AI ecosystem.", whoShouldCare: "AI infrastructure teams, cloud providers, hardware procurement", tags: '["amd","gpu","mi350","hardware","training"]', company: "AMD", importance: 70, novelty: 60, credibility: 82, impact: 68, practical: 55 },
    { idx: 73, title: "OpenAI o3 Reasoning Model Solves PhD-Level Science Problems", url: "https://openai.com/blog/o3-science", source: "openai_blog", sourceType: "blog", publishedAt: daysAgo(1), category: "model", aiSummary: "OpenAI demonstrates o3 solving complex PhD-level problems in physics, chemistry, and biology with step-by-step verifiable reasoning chains.", whyItMatters: "AI systems capable of graduate-level scientific reasoning could accelerate research across disciplines and serve as powerful research assistants.", whoShouldCare: "Scientists, research institutions, AI capability researchers", tags: '["o3","openai","reasoning","science","research"]', company: "OpenAI", modelFamily: "GPT", clusterId: clusterIds.gpt5, importance: 85, novelty: 78, credibility: 88, impact: 82, practical: 60 },
    { idx: 74, title: "Anthropic and Google Partner on AI Safety Benchmarks Initiative", url: "https://www.anthropic.com/news/safety-benchmarks-partnership", source: "anthropic_blog", sourceType: "blog", publishedAt: daysAgo(4), category: "policy", aiSummary: "Anthropic and Google announce a joint initiative to develop open-source AI safety evaluation benchmarks, inviting other labs and academic institutions to participate.", whyItMatters: "Cross-company collaboration on safety standards could accelerate responsible AI development and build a shared foundation for AI governance.", whoShouldCare: "AI safety community, policymakers, AI governance professionals", tags: '["safety","benchmarks","anthropic","google","collaboration"]', company: "Anthropic", importance: 70, novelty: 62, credibility: 90, impact: 68, practical: 50 },
  ];

  for (const item of itemData) {
    // Deduplicate URLs by appending index suffix for shared URLs
    let url = item.url;
    if (seenUrls.has(url)) {
      url = `${url}?item=${item.idx}`;
    }
    seenUrls.add(url);

    const imp = item.importance;
    const nov = item.novelty;
    const cred = item.credibility;
    const impact = item.impact;
    const prac = item.practical;
    const composite = compositeScore(imp, nov, cred, impact, prac);

    db.insert(items).values({
      id: itemIds[item.idx],
      title: item.title,
      url: url,
      source: item.source,
      sourceType: item.sourceType,
      publishedAt: item.publishedAt,
      discoveredAt: item.publishedAt,
      firstSeenAt: item.publishedAt,
      dateConfidence: "exact",
      category: item.category,
      aiSummary: item.aiSummary,
      whyItMatters: item.whyItMatters,
      whoShouldCare: item.whoShouldCare || null,
      tags: item.tags,
      company: item.company || null,
      modelFamily: item.modelFamily || null,
      clusterId: item.clusterId || null,
      isOpenSource: item.isOpenSource || false,
      importanceScore: imp,
      noveltyScore: nov,
      credibilityScore: cred,
      impactScore: impact,
      practicalScore: prac,
      compositeScore: composite,
      freshnessScore: 50,
      isOriginalSource: true,
      isPrimarySource: item.sourceType === "blog",
      isDemo: true,
      isBookmarked: false,
      isRead: false,
      isArchived: false,
    }).run();
  }

  // ─── Signals ──────────────────────────────────────────────────────
  const signalData = [
    {
      id: uuid(),
      title: "Reasoning Model Arms Race Accelerating",
      description: "GPT-5, Claude 4, and Gemini 2.5 all released within weeks of each other with major reasoning improvements, indicating an escalating competition for reasoning capabilities.",
      signalType: "acceleration",
      strength: 88,
      firstDetected: daysAgo(7),
      lastUpdated: daysAgo(0),
      relatedItemIds: JSON.stringify([itemIds[0], itemIds[4], itemIds[7]]),
      relatedEntities: JSON.stringify(["OpenAI", "Anthropic", "Google"]),
      tags: '["reasoning","competition","frontier-models"]',
      isActive: true,
    },
    {
      id: uuid(),
      title: "Open-Weight Models Closing Gap with Proprietary",
      description: "Llama 4, DeepSeek R2, and Qwen 2.5 Max demonstrate that open-weight models are within striking distance of proprietary alternatives on most benchmarks.",
      signalType: "convergence",
      strength: 82,
      firstDetected: daysAgo(10),
      lastUpdated: daysAgo(1),
      relatedItemIds: JSON.stringify([itemIds[10], itemIds[35], itemIds[19]]),
      relatedEntities: JSON.stringify(["Meta", "DeepSeek", "Alibaba"]),
      tags: '["open-source","convergence","competition"]',
      isActive: true,
    },
    {
      id: uuid(),
      title: "AI Agent Frameworks Going Mainstream",
      description: "OpenAI, Anthropic, and Microsoft all shipping production agent tools within the same month signals agents moving from research curiosity to production infrastructure.",
      signalType: "breakout",
      strength: 78,
      firstDetected: daysAgo(6),
      lastUpdated: daysAgo(0),
      relatedItemIds: JSON.stringify([itemIds[20], itemIds[21], itemIds[32]]),
      relatedEntities: JSON.stringify(["OpenAI", "Anthropic", "Microsoft"]),
      tags: '["agents","production","frameworks"]',
      isActive: true,
    },
    {
      id: uuid(),
      title: "On-Device AI Becoming Viable",
      description: "Apple, Samsung, and quantization advances are making capable AI models run on consumer devices, potentially shifting AI from cloud to edge.",
      signalType: "emerging_topic",
      strength: 65,
      firstDetected: daysAgo(8),
      lastUpdated: daysAgo(5),
      relatedItemIds: JSON.stringify([itemIds[31], itemIds[40], itemIds[11]]),
      relatedEntities: JSON.stringify(["Apple", "Samsung", "Meta"]),
      tags: '["on-device","edge-ai","mobile","hardware"]',
      isActive: true,
    },
    {
      id: uuid(),
      title: "AI Safety Regulation Crystallizing Globally",
      description: "EU AI Act enforcement, US AISI standards, and voluntary commitments are converging into a global regulatory framework for AI.",
      signalType: "convergence",
      strength: 72,
      firstDetected: daysAgo(12),
      lastUpdated: daysAgo(2),
      relatedItemIds: JSON.stringify([itemIds[13], itemIds[38], itemIds[64]]),
      relatedEntities: JSON.stringify(["EU", "US AISI"]),
      tags: '["regulation","safety","policy","global"]',
      isActive: true,
    },
    {
      id: uuid(),
      title: "Custom AI Silicon Challenging NVIDIA Dominance",
      description: "Groq, Cerebras, and AMD all making credible challenges to NVIDIA's AI chip dominance with different architectural approaches.",
      signalType: "emerging_topic",
      strength: 60,
      firstDetected: daysAgo(11),
      lastUpdated: daysAgo(2),
      relatedItemIds: JSON.stringify([itemIds[48], itemIds[55], itemIds[72]]),
      relatedEntities: JSON.stringify(["Groq", "Cerebras", "AMD", "NVIDIA"]),
      tags: '["hardware","chips","competition","infrastructure"]',
      isActive: true,
    },
    {
      id: uuid(),
      title: "AI Interpretability Research Advancing Rapidly",
      description: "Anthropic's scaling monosemanticity and DeepMind's causal analysis suggest mechanistic interpretability is becoming practical at frontier model scale.",
      signalType: "acceleration",
      strength: 70,
      firstDetected: daysAgo(5),
      lastUpdated: daysAgo(2),
      relatedItemIds: JSON.stringify([itemIds[60], itemIds[44]]),
      relatedEntities: JSON.stringify(["Anthropic", "Google"]),
      tags: '["interpretability","safety","research"]',
      isActive: true,
    },
  ];

  for (const s of signalData) {
    db.insert(signals).values({ ...s, isDemo: true }).run();
  }

  // ─── Alerts ───────────────────────────────────────────────────────
  const alertData = [
    { id: uuid(), type: "model_release", title: "GPT-5 Released by OpenAI", itemId: itemIds[0], severity: "critical", isRead: false, createdAt: daysAgo(2) },
    { id: uuid(), type: "model_release", title: "Claude 4 Released by Anthropic", itemId: itemIds[4], severity: "critical", isRead: true, createdAt: daysAgo(5) },
    { id: uuid(), type: "model_release", title: "Gemini 2.5 Pro Released by Google", itemId: itemIds[7], severity: "high", isRead: true, createdAt: daysAgo(4) },
    { id: uuid(), type: "model_release", title: "Llama 4 Open Weights Released by Meta", itemId: itemIds[10], severity: "high", isRead: true, createdAt: daysAgo(7) },
    { id: uuid(), type: "benchmark", title: "Claude 4 Sets New SWE-Bench Record", itemId: itemIds[5], severity: "medium", isRead: false, createdAt: daysAgo(4) },
    { id: uuid(), type: "paper", title: "Universal Prompt Injection Attack Discovered", itemId: itemIds[30], severity: "high", isRead: false, createdAt: daysAgo(4) },
    { id: uuid(), type: "product", title: "OpenAI Launches Operator Web Agent", itemId: itemIds[61], severity: "medium", isRead: false, createdAt: daysAgo(1) },
    { id: uuid(), type: "paper", title: "Self-Improving AI Agent Research Published", itemId: itemIds[56], severity: "high", isRead: false, createdAt: daysAgo(2) },
    { id: uuid(), type: "funding", title: "xAI Raises $6B at $50B Valuation", itemId: itemIds[25], severity: "medium", isRead: true, createdAt: daysAgo(10) },
    { id: uuid(), type: "product", title: "Anthropic Ships Claude Code", itemId: itemIds[21], severity: "medium", isRead: false, createdAt: daysAgo(3) },
    { id: uuid(), type: "benchmark", title: "AlphaProof v2 Achieves IMO Silver", itemId: itemIds[43], severity: "medium", isRead: false, createdAt: daysAgo(4) },
  ];

  for (const a of alertData) {
    db.insert(alerts).values({ ...a, isDemo: true }).run();
  }

  console.log(`Seeded ${itemData.length} items, ${clusterData.length} clusters, ${entityData.length} entities, ${signalData.length} signals, ${alertData.length} alerts.`);
}

// Run standalone with tsx
seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
